# Generated by Django 5.0.3 on 2024-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomimic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Biomimic_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
