# Generated by Django 5.0.3 on 2024-03-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_biomimic'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomimic',
            name='molecule_fct',
            field=models.CharField(choices=[('Antioxydant', 'Antioxydant'), ('Antibiotique', 'Antibiotique'), ('Antifongique', 'Antifongique'), ('Analgésique', 'Analgésique')], default='Make a Choice', max_length=50),
        ),
    ]
