# Generated by Django 5.0.3 on 2024-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_biomimic_molecule_fct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomimic',
            name='molecule_fct',
            field=models.CharField(blank=True, choices=[('Antioxydant', 'Antioxydant'), ('Antibiotique', 'Antibiotique'), ('Antifongique', 'Antifongique'), ('Analgésique', 'Analgésique')], max_length=50, null=True),
        ),
    ]
